# Generated by Django 5.2.1 on 2025-05-25 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailtable',
            name='eventdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='eventname',
            field=models.CharField(max_length=20),
        ),
    ]
