# Generated by Django 5.2.1 on 2025-05-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventdetailtable_eventdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonsurname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='eventcategory',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='eventdescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='eventstatus',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='eventtype',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
