# Generated by Django 5.2.1 on 2025-05-25 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eventdetailtable_contactpersonname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('othernames', models.CharField(max_length=99, null=True)),
                ('initials', models.CharField(max_length=10, null=True)),
                ('preferredname', models.CharField(max_length=50, null=True)),
                ('homelanguage', models.CharField(max_length=50, null=True)),
                ('preferredlanguage', models.CharField(max_length=50, null=True)),
                ('maidenname', models.CharField(max_length=50, null=True)),
                ('countryofissue', models.CharField(max_length=50)),
                ('typefld', models.CharField(max_length=50)),
                ('disabled', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantstatus', models.CharField(max_length=50, null=True)),
                ('eventstatus', models.CharField(max_length=50, null=True)),
                ('eventlinkdate', models.DateTimeField(max_length=50)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventdetailtable')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participanttable')),
            ],
        ),
    ]
