# Generated by Django 5.2.1 on 2025-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_participanttable_eventparticipanttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttable',
            name='events',
            field=models.ManyToManyField(to='api.eventdetailtable'),
        ),
        migrations.AlterField(
            model_name='participanttable',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EventParticipantTable',
        ),
    ]
