# Generated by Django 5.2.1 on 2025-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participanttable_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttable',
            name='startPointLat',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='participanttable',
            name='startPointLng',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
    ]
