# Generated by Django 5.2.3 on 2025-06-21 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_participanttable_startpointlat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventMainImg', models.ImageField(upload_to='images/eventsmain/')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.eventdetailtable')),
            ],
        ),
    ]
