# Generated by Django 5.2.3 on 2025-06-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_eventimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.eventdetailtable'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='eventMainImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/eventsmain/'),
        ),
    ]
