# Generated by Django 5.2.3 on 2025-07-07 14:28

import api.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_eventimages_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonaddr1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonaddr2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonaddr3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonaddr4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonaddrcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonaddrtype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersoncitizenship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersoncountry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonemailaddr',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonnationality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonothername',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonphonenum',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='contactpersonprovince',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventdetailtable',
            name='terminationstatus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='eventcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='eventstatus',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Planning'), (2, 'RegistrationOpen'), (3, 'RegistrationClosed'), (4, 'Completed'), (5, 'Closed')], default=api.util.EventStatus['Created']),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='eventtype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
