# Generated by Django 5.2.3 on 2025-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_eventdetailtable_contactpersonaddr1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailtable',
            name='eventcategory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='eventtype',
            field=models.CharField(max_length=50),
        ),
    ]
