# Generated by Django 5.2.3 on 2025-07-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_eventdetailtable_eventcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailtable',
            name='eventname',
            field=models.CharField(max_length=50),
        ),
    ]
