# Generated by Django 5.2.3 on 2025-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_eventdetailtable_eventname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonaddr1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonaddr2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonaddr3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonaddr4',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonaddrcode',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonaddrtype',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersoncitizenship',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersoncountry',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonemailaddr',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonnationality',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonothername',
            field=models.CharField(blank=True, default='', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonphonenum',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='contactpersonprovince',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetailtable',
            name='terminationstatus',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
