# Generated by Django 5.2.3 on 2025-07-07 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_eventdetailtable_contactpersonaddr1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailtable',
            name='eventenddate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
