# Generated by Django 5.2.3 on 2025-07-12 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_eventdetailtable_eventenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttable',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
