# Generated by Django 5.2.3 on 2025-07-12 08:08

import api.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_participanttable_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttable',
            name='gender',
            field=models.IntegerField(choices=api.util.Gender.choices, default=api.util.Gender['notDefined']),
        ),
    ]
