# Generated by Django 5.2.3 on 2025-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_participanttable_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttable',
            name='emailaddress',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participanttable',
            name='usrphonenum',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
