# Generated by Django 5.2.3 on 2025-07-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_participanttable_emailaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttable',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profilepic/'),
        ),
    ]
