# Generated by Django 5.2.3 on 2025-08-03 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_participanttable_profilepic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttable',
            name='authid',
            field=models.CharField(default=31397439739854810, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participanttable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
