# Generated by Django 5.2.3 on 2025-09-21 19:13

import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_participanttable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='eventMainImg',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/eventsmain/'),
        ),
        migrations.AlterField(
            model_name='participanttable',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/profilepic/'),
        ),
    ]
