# Generated by Django 5.2.3 on 2025-10-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_eventimages_eventmainimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubDetailTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eventsubdate', models.DateField()),
                ('regfees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regfeescurrency', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevent', to='api.eventdetailtable')),
            ],
        ),
    ]
