# Generated by Django 5.2.3 on 2025-10-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_eventsubdetailtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPaymRefTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=99, null=True)),
                ('m_paym_id', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_timestamp', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=10, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Participant', to='api.participanttable')),
            ],
        ),
    ]
