# Generated by Django 5.2.3 on 2025-10-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_participantpaymreftable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantpaymreftable',
            name='m_paym_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
