# Generated by Django 5.2.3 on 2025-10-25 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_participantpaymreftable_m_paym_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantEventTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('eventregdate', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventdetailtable')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participanttable')),
                ('paymref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.participantpaymreftable')),
                ('subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventsubdetailtable')),
            ],
        ),
    ]
