# Generated by Django 5.2.3 on 2026-01-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_participanteventtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventimage_event', to='api.eventdetailtable'),
        ),
        migrations.AlterField(
            model_name='eventsubdetailtable',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevent_event', to='api.eventdetailtable'),
        ),
        migrations.AlterField(
            model_name='participanteventtable',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantevent_event', to='api.eventdetailtable'),
        ),
        migrations.AlterField(
            model_name='participanteventtable',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantevent_participant', to='api.participanttable'),
        ),
        migrations.AlterField(
            model_name='participanteventtable',
            name='paymref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participantevent_paymref', to='api.participantpaymreftable'),
        ),
        migrations.AlterField(
            model_name='participanteventtable',
            name='subevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantevent_subevent', to='api.eventsubdetailtable'),
        ),
        migrations.AlterField(
            model_name='participanttable',
            name='authid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participanttable',
            name='emailaddress',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
