# Generated by Django 5.2.3 on 2026-04-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_eventimages_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanttable',
            name='authid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EventNotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventnotification_event', to='api.eventdetailtable')),
            ],
        ),
    ]
