# Generated by Django 5.2.3 on 2026-04-19 13:09

import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_participanttable_authid_eventnotificationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotificationtable',
            name='notificationImg',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/notificationImg/'),
        ),
    ]
