# Generated by Django 5.2.3 on 2026-05-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_eventnotificationtable_notificationimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventcategory_event', to='api.eventdetailtable')),
            ],
        ),
    ]
