# Generated by Django 5.2.3 on 2026-05-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_eventcategorytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubdetailtable',
            name='eventcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subevent_eventcategory', to='api.eventcategorytable'),
            preserve_default=False,
        ),
    ]
