# Generated by Django 5.2.3 on 2026-05-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_eventsubdetailtable_eventcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategorytable',
            name='event',
        ),
    ]
