# Generated by Django 5.2.3 on 2026-05-05 17:04

import api.util
import django.db.models.deletion
import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_eventcategorytable_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSponsorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsorImg', models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/notificationImg/')),
                ('sponsorcategory', models.IntegerField(choices=[(0, 'notDefined'), (1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary')], default=api.util.SponsorCategory['notDefined'])),
            ],
        ),
        migrations.AddField(
            model_name='eventsubdetailtable',
            name='displaysequence',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EventSponsorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsorImg', models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/notificationImg/')),
                ('sponsorcategory', models.IntegerField(choices=[(0, 'notDefined'), (1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary')], default=api.util.SponsorCategory['notDefined'])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventsponsor_event', to='api.eventdetailtable')),
            ],
        ),
    ]
