# Generated by Django 5.2.3 on 2026-05-05 18:07

import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_appsponsortable_eventsubdetailtable_displaysequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsponsortable',
            name='sponsorImg',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/appsponsorImg/'),
        ),
        migrations.AlterField(
            model_name='eventsponsortable',
            name='sponsorImg',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/eventsponsorImg/'),
        ),
    ]
