# Generated by Django 5.2.3 on 2026-05-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_appsponsortable_sponsorimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsponsortable',
            name='externallink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsponsortable',
            name='externallink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
