# Generated by Django 5.2.3 on 2026-06-21 13:33

import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_appsponsortable_externallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubdetailtable',
            name='elevationImg',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/subeventsElevationImg/'),
        ),
    ]
