# Generated by Django 5.2.3 on 2026-06-28 11:58

import django.db.models.deletion
import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_eventsubdetailtable_elevationimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInformationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('infoImg', models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/eventInformationImg/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventinfo_event', to='api.eventdetailtable')),
            ],
        ),
    ]
