# Generated by Django 5.2.3 on 2026-07-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_eventinformationtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanteventtable',
            name='paymref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participantevent_paymref', to='api.participantpaymreftable'),
        ),
        migrations.AlterField(
            model_name='participanttable',
            name='authid',
            field=models.CharField(max_length=50),
        ),
    ]
