# Generated by Django 5.2.3 on 2026-07-24 20:37

import api.util
import django.db.models.deletion
import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_participanteventtable_paymref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contactperson', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('address3', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('logo', models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/clubLogo/')),
                ('banner', models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/clubBanner/')),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=api.util.ClubStatus['Active'])),
            ],
        ),
        migrations.CreateModel(
            name='ClubMemberTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Pending')], default=api.util.ClubMemberStatus['Pending'])),
                ('role', models.IntegerField(choices=[(0, 'Member'), (1, 'Admin'), (2, 'Secretary'), (3, 'Director'), (4, 'Owner')], default=api.util.ClubMemberRole['Member'])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubmember_participant', to='api.participanttable')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubmember_club', to='api.clubtable')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('club', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='ClubEventTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubevent_event', to='api.eventdetailtable')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubevent_club', to='api.clubtable')),
            ],
            options={
                'unique_together': {('club', 'event')},
            },
        ),
    ]
