# Generated by Django 5.2.3 on 2026-07-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_club_to_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailtable',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='event_organisation', to='api.organisationtable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationeventtable',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisationevent_event', to='api.eventdetailtable'),
        ),
        migrations.AlterField(
            model_name='organisationeventtable',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisationevent_organisation', to='api.organisationtable'),
        ),
        migrations.AlterField(
            model_name='organisationmembertable',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisationmember_organisation', to='api.organisationtable'),
        ),
        migrations.AlterField(
            model_name='organisationmembertable',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisationmember_participant', to='api.participanttable'),
        ),
    ]
