# Generated by Django 5.2.3 on 2026-08-08 12:03

import api.util
import utilities.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_errortable_app_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleticorganisationtable',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/AthleticOrgBanner/'),
        ),
        migrations.AlterField(
            model_name='athleticorganisationtable',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=utilities.storage_backends.PrivateMediaStorage(), upload_to='images/AthelicOrgLogo/'),
        ),
        migrations.AlterField(
            model_name='errortable',
            name='app_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmembertable',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Pending'), (3, 'expired'), (4, 'rejected'), (5, 'cancelled'), (6, 'suspended'), (7, 'terminated'), (8, 'onhold')], default=api.util.OrganisationMemberStatus['Pending']),
        ),
    ]
