# Generated by Django 5.2.3 on 2026-08-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_athleticorganisationtable_banner_and_more'),
        ('api', '0054_errortable_app_build_environment_version_label'),
    ]

    operations = [
    ]
