# Generated by Django 5.2.3 on 2026-10-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_participantnotificationreadtable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='participantnotificationreadtable',
            new_name='api_partici_partici_3dde54_idx',
            old_name='api_partici_partici_8a4f2d_idx',
        ),
        migrations.AlterField(
            model_name='errortable',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
